"""empty message

Revision ID: 414e45e36045
Revises: 1acd783ef03e
Create Date: 2022-12-05 13:04:30.418763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '414e45e36045'
down_revision = '1acd783ef03e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peopleFav',
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('users_id', 'people_id')
    )
    op.create_table('planetsFav',
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('planets_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planets_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('users_id', 'planets_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planetsFav')
    op.drop_table('peopleFav')
    # ### end Alembic commands ###
