"""empty message

Revision ID: 993ebe6be3a3
Revises: 414e45e36045
Create Date: 2022-12-05 16:34:08.921070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993ebe6be3a3'
down_revision = '414e45e36045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peopleFav', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('peopleFav_users_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('users_id')

    with op.batch_alter_table('planetsFav', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('planetsFav_users_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('users_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planetsFav', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('planetsFav_users_id_fkey', 'user', ['users_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('peopleFav', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('peopleFav_users_id_fkey', 'user', ['users_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
